// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAlAS0Fz5KgAtEanPDIbN_aOPCZ1uqYws',
    appId: '1:900853072435:web:98747c16f20aa44e23d946',
    messagingSenderId: '900853072435',
    projectId: 'ecommerce-36d06',
    authDomain: 'ecommerce-36d06.firebaseapp.com',
    databaseURL: 'https://ecommerce-36d06-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-36d06.appspot.com',
    measurementId: 'G-ZZYFPWJGCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtGqwNds8aCOZQ1WotjfWPp4CNVmaDhaE',
    appId: '1:900853072435:android:97370f1395d36ec523d946',
    messagingSenderId: '900853072435',
    projectId: 'ecommerce-36d06',
    databaseURL: 'https://ecommerce-36d06-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-36d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUVDEVHFIdXXcwvhxics6eAFT3olxghrg',
    appId: '1:900853072435:ios:8c185167b847691123d946',
    messagingSenderId: '900853072435',
    projectId: 'ecommerce-36d06',
    databaseURL: 'https://ecommerce-36d06-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-36d06.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );
}
